### ISSUE TITLE
Creation of secret fails

### ISSUE THREAD

**Issue by julianblue** [developmentseed/eoapi-template#22]
Hi, 
I am deploying the demo template to my aws account and am receiving the following issue in the deployment. 

```bash
1:18:40 PM | CREATE_FAILED        | AWS::SecretsManager::Secret
| pgstac-db/bootstra...ac-instance/secret
Attribute 'Endpoint.Address' does not exist
```

```bash
 ❌  eoapi-template-demo-test-pgSTAC-infra failed: Error: The stack named eoapi-template-demo-test-pgSTAC-infra failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_FAILED (The following resource(s) failed to delete: [pgstacdbEAADF705]. ): Attribute 'Endpoint.Address' does not exist, Instance eoapi-template-demo-test-pgstac-infra is currently creating - a final snapshot cannot be taken. (Service: Rds, Status Code: 400, Request ID: xxxxxxxxxxxxxxxxxxxxx)
    at FullCloudFormationDeployment.monitorDeployment (/Users/julianblau/Projects/eoapi-template/node_modules/aws-cdk/lib/index.js:443:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/julianblau/Projects/eoapi-template/node_modules/aws-cdk/lib/index.js:446:153546)
    at async /Users/Projects/eoapi-template/node_modules/aws-cdk/lib/index.js:446:136809
```

Am I missing anything ?

**Comment by vincentsarago** [comment]
thanks for the report @julianblue 🙏 

We're currently moving a lot of things around so the repo should be considered WIP 

we hope to have everything done by the end of the week.

**Comment by julianblue** [comment]
@vincentsarago great news !

FYI, I see this happening when setting the AWS_REGION and AWS_DEFAULT_REGION to eu-central-1. So leaving these variables blank there are no issues. Maybe there is some internal configuration that creates the secrets in another region and therefore the endpoint address cannot be found.

**Comment by emileten** [comment]
Thanks for the report ! The same thing happened to me yesterday when [deploying from here](https://github.com/developmentseed/eoapi-cdk/commit/bb24dedb1bf8cf02bb13c028f2fe38759dcc0360#diff-80a656ce3173ad8023b282907e390f7642e5a0d1edd6ef37f64e5f4de4a49584). I bumped the `cdk` node CLI package I was using from 2.128.0 to 2.129.0 and it fixed this issue 🤷‍♂️ 

Like vincent said this repo is going to change susbstantially this week, and most likely, the CDK code will resemble the one here https://github.com/developmentseed/eoapi-cdk/tree/main/integration_tests/cdk.

**Comment by vincentsarago** [comment]
the last merge updates eoapi-cdk (and thus cdk version), I've deployed it on a clean env and wasn't able to reproduce this issue.

going to close this now but feel free to reopen 🙏
